global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'ai_worker'
    static_configs:
      - targets: ['ai_worker:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 